import "@/app/globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "@/app/api/routes/page"

export const metadata = {
  title: "Next js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <ToastContainer />
      </body>
    </html>
  )
}